import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import localFont from 'next/font/local'
import Providers from "@/Component/Provider/Providerr";



const myFont = localFont({
  src: '../static-fonts/Poppins-Regular.otf',
  display: 'swap'
})


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Providers>
        <body className={myFont.className}>{children}</body>
      </Providers>
    </html>
  );
}
